CREATE PROCEDURE SP_MEDICO_IN_UP
@MED_INT_ID INT
,@MED_STR_NOME VARCHAR(70)
,@RETURN VARCHAR(200) OUTPUT
AS
BEGIN TRY
IF EXISTS (SELECT MED_INT_ID FROM MEDICO WHERE MED_INT_ID = @MED_INT_ID)
BEGIN
-- UPDATE
UPDATE MEDICO
SET MED_STR_NOME = @MED_STR_NOME
WHERE MED_INT_ID = @MED_INT_ID;
SET @RETURN = 'Solicitação realizada com sucesso. Registro atualizado.';



END
ELSE
BEGIN
-- INSERT
INSERT INTO MEDICO (MED_STR_NOME) VALUES (@MED_STR_NOME);
SET @RETURN = 'Solicitação realizada com sucesso. Registro salvo.';
END;
END TRY
BEGIN CATCH
SET @RETURN = 'Erro! Solicitação não foi concluída. ' + ERROR_MESSAGE();
END CATCH;
